class_name JournalExporter
extends RefCounted
## JournalExporter — menulis seluruh isi jurnal Ardi ke berkas Markdown di
## user://exports/. Berguna sebagai kenang-kenangan perjalanan (dan debugging).

const EXPORT_DIR := "user://exports"


static func export_markdown() -> String:
	var dm := DataManager
	var gm := GameManager
	var im := InvestigationManager
	var rm := RelationshipManager
	var sm := SaveManager
	var en: bool = dm.language == "en"
	var lines: PackedStringArray = []
	lines.append("# THE LAST MEMORY — %s" % ("Ardi's Journal" if en else "Jurnal Ardi"))
	lines.append("")
	lines.append("- %s: %s" % ["Date" if en else "Tanggal", Time.get_datetime_string_from_system(false, true)])
	lines.append("- %s: %s" % ["Chapter" if en else "Bab", dm.tr_key("chapter_" + gm.current_chapter)])
	lines.append("- %s: %s" % ["Location" if en else "Lokasi", str((dm.get_scene_data(gm.current_location) as Dictionary).get("name", gm.current_location))])
	lines.append("- %s: %s" % ["Playtime" if en else "Waktu main", MathUtils.format_playtime(sm.playtime)])
	lines.append("- %s: %d%%" % ["Completion" if en else "Penyelesaian", gm.completion_percent()])
	if gm.hard_mode:
		lines.append("- Mode Detektif")
	if gm.new_game_plus:
		lines.append("- New Game+")
	lines.append("")
	# Petunjuk.
	var prog: Dictionary = im.clue_progress()
	lines.append("## %s (%d/%d)" % ["Clues" if en else "Petunjuk", int(prog.get("found", 0)), int(prog.get("total", 0))])
	for cid in im.clues_found:
		var c: Dictionary = dm.get_clue(str(cid))
		var loc: String = str((dm.get_scene_data(str(c.get("found_in", ""))) as Dictionary).get("name", ""))
		lines.append("- **%s** _(%s)_ — %s" % [str(c.get("name", cid)), loc, str(c.get("description", ""))])
	lines.append("")
	# Deduksi.
	lines.append("## %s (%d/%d)" % ["Deductions" if en else "Deduksi", (im.deductions_solved as Array).size(), dm.deductions.size()])
	for did in im.deductions_solved:
		var d: Dictionary = dm.get_deduction(str(did))
		lines.append("- **%s** — %s" % [str(d.get("title", did)), str(d.get("conclusion", ""))])
	lines.append("")
	# Hubungan.
	lines.append("## %s" % ("Relationships" if en else "Hubungan"))
	for cid in ["rara", "pak_harto", "mira", "bu_rt"]:
		if cid in (im.characters_met as Array):
			lines.append("- %s: %d" % [str((dm.get_character(cid) as Dictionary).get("name", cid)), rm.get_value(cid)])
	lines.append("")
	# Linimasa.
	lines.append("## %s" % ("Timeline" if en else "Linimasa"))
	var events: Array = (im.timeline_events as Array).duplicate()
	events.sort_custom(func(a: Variant, b: Variant) -> bool: return str((a as Dictionary).get("year", "")) < str((b as Dictionary).get("year", "")))
	for ev in events:
		lines.append("- **%s** — %s" % [str((ev as Dictionary).get("year", "")), str((ev as Dictionary).get("text", ""))])
	lines.append("")
	# Catatan.
	lines.append("## %s" % ("Notes" if en else "Catatan"))
	for n in im.journal_notes:
		var nd: Dictionary = n
		var src: String = str(nd.get("source", ""))
		lines.append("- %s%s" % [("[" + src + "] ") if src != "" else "", str(nd.get("text", ""))])
	lines.append("")
	# Pilihan.
	lines.append("## %s (%d)" % ["Choices" if en else "Pilihan", (DialogueManager.history as Array).size()])
	for h in DialogueManager.history:
		var hd: Dictionary = h
		lines.append("- `%s` → %s" % [str(hd.get("node", "")), str(hd.get("text", ""))])
	lines.append("")
	# Momen & foto.
	lines.append("## %s (%d/%d)" % ["Moments" if en else "Momen", (im.moments_taken as Array).size(), dm.moments.size()])
	for mid in im.moments_taken:
		lines.append("- %s" % str((dm.moments.get(str(mid), {}) as Dictionary).get("name", mid)))
	if not (PhotoManager.photos as Array).is_empty():
		lines.append("")
		lines.append("## %s (%d)" % ["Photos" if en else "Foto", (PhotoManager.photos as Array).size()])
		for f in PhotoManager.photos:
			lines.append("- `%s`" % str(f))
	# Pencapaian & ending.
	lines.append("")
	lines.append("## %s (%d/%d)" % ["Achievements" if en else "Pencapaian", (AchievementManager.unlocked as Array).size(), dm.achievements.size()])
	for a in AchievementManager.unlocked:
		var ad: Dictionary = dm.get_achievement(str(a))
		lines.append("- 🏆 %s" % str(ad.get("name_en", ad.get("name", a)) if en else ad.get("name", a)))
	if not (gm.endings_seen as Array).is_empty():
		lines.append("")
		lines.append("## %s" % ("Endings seen" if en else "Ending yang disaksikan"))
		for e in gm.endings_seen:
			var ed: Dictionary = dm.get_ending(str(e))
			lines.append("- %s %s" % [str(ed.get("art", "")), str(ed.get("title_en", ed.get("title", e)) if en else ed.get("title", e))])
	lines.append("")
	lines.append("_%s_" % ("Generated by THE LAST MEMORY." if en else "Dibuat oleh THE LAST MEMORY."))
	var stamp := Time.get_datetime_string_from_system().replace(":", "").replace("-", "").replace(" ", "_")
	var path := "%s/jurnal_%s.md" % [EXPORT_DIR, stamp]
	if not SaveUtils.write_text_file(path, "\n".join(lines)):
		return ""
	return path
